### ISSUE TITLE
Feature request: Appearance settings

### ISSUE THREAD

**Issue by archisman-panigrahi** [luisbocanegra/plasma-cursor-eyes#2]
In your screenshots, the color of the eyeballs is white, while in my computer, it is blue.

Is it possible to change the appearance of the eye, especially the Tango theme? https://gitlab.xfce.org/panel-plugins/xfce4-eyes-plugin/-/tree/master/themes/Tango?ref_type=heads

**Comment by luisbocanegra** [comment]
Currently the colors come from the plasma theme/color scheme. Will add more customization sizes/color and even loading custom images after fixing vertical panels and adding some checks for the background D-Bus service and KWin script status

**Comment by luisbocanegra** [comment]
Hi please try the latest changes

Added

- Eyes count
- Eyes spacing
- Custom shape for the eyeball and iris, just like xfce4-eyes but doesn't support non-circular shapes
- Iris size
- Pupil size
- Border
- Scaling
- Text size

![Screenshot_20240725_091440](https://github.com/user-attachments/assets/00443695-1f28-478b-9acf-e63941d35857)

**Comment by luisbocanegra** [comment]
Also added some prebuilt themes from gnome-applet, mate-applet and lxqt-plugin-qeyes

![Screenshot_20240726_020334](https://github.com/user-attachments/assets/d7b86229-2c2a-428e-a22a-d057a08e4cef)

Closing this as completed

**Comment by archisman-panigrahi** [comment]
Looks great! Thank you
